### PR TITLE
W6M3 - Updates and Maintenance 01/05/24

### LINKED ISSUE #223: W6M3 - Warning about multiple competing values for 'toolbar.active_drag' (to be addressed before 4th iteration)
The warning looks like this:

/usr/local/lib/python3.10/dist-packages/malariagen_data/anoph/h12.py:455: UserWarning: found multiple competing values for 'toolbar.active_drag' property; using the latest value
  fig = bokeh.layouts.gridplot(

It is not a big issue but it kind of messes up the output when there are several plots drawn one after another.

### PR DESCRIPTION
**Pull request by jonbrenas**
Addresses #193 for this module.
Addresses #199 for this module.
Addresses #224 for this module.

Resolves  #223 (temporarily). I actually removed all warnings to avoid the pandas and bokeh warnings as well. There is a note saying "Note: you may need to restart the kernel to use updated packages." that I am not found of but I can't get rid of.

### CODE REVIEW

**Comment by jonbrenas** [comment]
#233 needs to be addressed before reviews so I have suspended the request.

**Comment by jonbrenas** [comment]
The links to the figures have been corrected.

**Review by ahernank — COMMENTED** [review]
Thanks @jonbrenas! Very minor, the link on paper for `For a deeper dive in the statistic and it's underlying mathematics, I would highly recommend the Garud lab website or for the brave, the paper.` has a leading https, so it is not redirecting correctly; it also seems that the image below didn't fully render but this might just be the view here and suspect the HTML looked fine when building.

**Comment by ahernank** [comment]
Thanks @jonbrenas, we are just missing the small URL typo above & we should be able to merge.

**Review by ahernank — APPROVED** [review]

**Pull request merged**
