### PR TITLE
W5M4 update

### PR DESCRIPTION
**Pull request by KellyLBennett**
Warnings hidden when generating heterozygosity plots resolves issue #235. Also addresses issues #193 #199 #224.

There is an image that appears to be missing above exercise 3, but is also missing on the website currently. I will open another issue for this.

### CODE REVIEW

**Comment by ahernank** [comment]
Thanks @Kelly, there are some extra NBs that you might not want on this PR. 

Do you happen to know which image is missing? Is it on the recording? Might be good to track it down to get it back in there.

**Comment by KellyLBennett** [comment]
@ahernank I think the changes on the other notebooks included are OK so perhaps we can just merge this as I am not sure where these extra notebooks are coming from. 

It looks like the image is an ROH plot?

Screenshot 2024-05-07 at 09 43 39

**Comment by cclarkson** [comment]
Hi @KellyLBennett, the extra notebooks/files on a commit usually come from being "touched", _i.e_. they have been opened, which changes their timestamp, even though no code changes have been made. When adding files to a commit (`git add`), it is usually best to add them individually, rather than add all (`git add -A`), as you end up including files that you haven't worked on,

To ensure that errors or out-of-date versions of files don't get pushed back to the repo, we only merge branches with files that that have been modified. This also makes it much easier to review the changes made.

**Comment by KellyLBennett** [comment]
OK thanks @cclarkson building a new branch.

**Pull request closed without merging**
