### PR TITLE
W6M4 - Updates and Maintenance 30/04/24

### PR DESCRIPTION
**Pull request by jonbrenas**
Addresses #193 for this module.
Addresses #199 for this module.
Addresses #224 for this module.

I moved `import malariagen_data` in its own cell right after the word about authentication as it made it clearer (imho) what the authentication is for.

There is still (it might actually be new) a warning about the absence of a project ID. It doesn't cause any issue and setting a project for gcloud doesn't sound crucial but I can make changes to get rid of the warning if we think it would be better.

### CODE REVIEW

**Review by ahernank — COMMENTED** [review]
Thanks @jonbrenas, it seems that some of the images here are not rendering (but as discussed, these seem to be okay on the local html, so we can merge these & see how it works). Might be good to understand where the import warning is coming from.

**Comment by ahernank** [comment]
Thanks @jonbrenas, I've just ran this one on Colab and the warnings related to project ID are not showing there. It might be good to understand why we are getting this one on the development environment and/or suppress to avoid confusion from trainees looking at the HTML.

**Comment by jonbrenas** [comment]
Thanks @ahernank ! I think the Warning was absent in my latest commit (it might be silenced after the first time it is run)

**Review by ahernank — APPROVED** [review]

**Comment by ahernank** [comment]
Is it the case that this isn't on the HTML? I think it is still there during import and API calling. 
Screenshot 2024-05-13 at 09 21 33
Screenshot 2024-05-13 at 09 22 20

**Comment by jonbrenas** [comment]
Thanks @ahernank. Using AnoPrimer instead of AgamPrimer solved the BLAT issue and I found a solution for the project ID thing as well. I am waiting for plotly to decide to render the plots properly and I'll push a usable version of the notebook. I don't think we will have time to amend the videos to use the correct package, however.

**Review by ahernank — COMMENTED** [review]
Thanks so much for chasing those errors, @jonbrenas. 

Just on the env variable, I agree that including:
```
import os
os.environ["GOOGLE_CLOUD_PROJECT"] = "PAMCA-W6M7-AnoPrimer"
```
deals with the project ID warning. But, in Colab, you don't get this warning. I'm wondering if it would be best to take out this code block to avoid introducing confusion around the google cloud project, and run the block twice to render the html here to silence these warnings. We can add a small comment within the import code block, saying that if you get the no project_ID message, it is safe to ignore.

**Comment by jonbrenas** [comment]
Thanks @ahernank. For some reason, the warning appears thrice now (twice when the packages are imported and once when ag3 is instantiated). Rerunning the cell with the imports removes the warnings but not rerunning the instantiation so the HTML would have to include the warning at least once if we get read of this code.

**Comment by ahernank** [comment]
Thanks @jonbrenas, I think having the one warning is okay, we can still add a comment within the code to say that it is safe to ignore this. I think this is easier than explaining the project ID env var.

**Review by ahernank — APPROVED** [review]
Thanks @jonbrenas!

**Pull request merged**
