### PR TITLE
W5M1 update

### LINKED ISSUE #216: W5M1 access CNV calls
An error encountered trying to access all CNV calls (trying to access an unavailable sample set).

ds_cnv = ag3.cnv_hmm(
    region="3R"
)
ds_cnv

The error....

`KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/malariagen_data/anoph/cnv_data.py](https://v071txj69d-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240418-060126_RC00_625982099#) in open_cnv_hmm(self, sample_set)
     77         try:
---> 78             return self._cache_cnv_hmm[sample_set]
     79         except KeyError:

KeyError: '1188-VO-NIANG-NIEL-SN-2304-VMF00259'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
21 frames
<decorator-gen-119> in _request(self, method, path, headers, json, data, *args, **kwargs)

FileNotFoundError: https://storage.googleapis.com/download/storage/v1/b/vo_agam_release/o/v3.10%2Fcnv%2F1188-VO-NIANG-NIEL-SN-2304-VMF00259%2Fhmm%2Fzarr%2F.zmetadata?alt=media

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
KeyError: '.zmetadata'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/malariagen_data/util.py](https://v071txj69d-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240418-060126_RC00_625982099#) in __getitem__(self, key)
    126             except KeyError as e:
    127                 # raise a different error to ensure zarr propagates the exception, rather than filling
--> 128                 raise FileNotFoundError(e)
    129 
    130         def __contains__(self, key):

FileNotFoundError: '.zmetadata'`

### PR DESCRIPTION
**Pull request by KellyLBennett**
Changes to sample_set and global changes outlined in issues #193 #199 #224.

Warning below also supressed. /home/conda/developer/2835ffd46e5535e81e9672d0828c143d4f1444491ac44f0aeddd90156919e446-20240426-081151-481742-64-training-nb-maintenance-mgen-9.0.0/lib/python3.10/site-packages/malariagen_data/anoph/snp_frq.py:1203: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'Y' instead. return pd.Period(freq="A", year=year)

Resolves #216

### CODE REVIEW

**Comment by KellyLBennett** [comment]
@ahernank It looks like the missing images are these (taken as screenshots from the video).

Screenshot 2024-05-07 at 09 48 46
Screenshot 2024-05-07 at 09 49 25

**Comment by KellyLBennett** [comment]
Do you know how to fix these images?

**Comment by KellyLBennett** [comment]
The URLs in the notebook.

**Review by ahernank — COMMENTED** [review]
Thanks @KellyLBennett. It seems that some of the URLs related to documentation are broken, e.g. https://malariaatlas.org/research-project/metrics-of-insecticide-treated-nets-distribution/ -- it would be great to update this (and any other, if there are) to reflect the current location of this data.

**Review by ahernank — APPROVED** [review]

**Pull request merged**
