### PR TITLE
W5M3 update

### LINKED ISSUE #220: W5M3 video colab discrepancies
There are differences throughout module 3 in the pivot tables and bar plots shown in the video and demonstrated with the notebook. This is because there are now many more samples in the Tanzanian, Kenya and Ugandan datasets compared to previously. Due to the larger number of samples,  looking at diversity statistics for the East African region takes a very long time to run.  There is also a different background on the maps shown in the video. A quick fix would be to restrict the data analysis in the notebook to the previous dataset, but requires further discussion.

### PR DESCRIPTION
**Pull request by KellyLBennett**
Data analysis has been restricted to release 3.0 to match the video examples. I also changed the map background to match. I would be grateful for a review @ahernank @jonbrenas and then I will run it in colab again to double check it. Resolves #220.

### CODE REVIEW

**Comment by ahernank** [comment]
Thanks @KellyLBennett! 

Some small things, would it be possible to rename this PR to start with W5M3? This makes it easier to review all notebooks on the same workshop together. 

Also, I think the notebook here wasn't run on the developer environment with the latest API version, this is `developer-training-nb-maintenance-mgen-9.0.0` on bespin. Would it be possible to re-run it using this environment to ensure we are testing all notebooks on this version?

Please do feel free to open other PRs for the other modules on W5 (if required), and we can also look at those together.

**Comment by KellyLBennett** [comment]
Thanks @ahernank I have run the notebook in developer-training-nb-maintenance-mgen-9.0.0. The rendering of the notebook is OK in terms of all analysis output but seems to add in some code boxes even though these are not present in the notebook. I am not sure how to resolve this.

**Comment by ahernank** [comment]
Thanks @KellyLBennett, yes, we've noticed the issue with the code boxes. Currently, we are leaving it unaddressed but it would be good to track it down & fix it before the next iteration.

**Review by ahernank — COMMENTED** [review]
Thanks @KellyLBennett. A small note, as the cohorts data now includes quarter data, it would be good to reflect that these columns exist on the text below: 

> If you scroll to the right, you'll see columns named "cohort_admin1_year", "cohort_admin1_month", **"cohort_admin1_quarter",** "cohort_admin2_year", **"cohort_admin2_quarter",** and "cohort_admin2_month". Each of these columns provides a different set of cohort labels. All are grouped by species (taxon).

**Review by ahernank — APPROVED** [review]
Thanks @KellyLBennett, looks great! 

Just before merging, can I double check that the NB with the latest fixes has rendered correctly when checking it with `jb build docs` (after cleaning with `jb clean docs`)?

**Comment by KellyLBennett** [comment]
Yes all seemed to render fine for me.

**Comment by ahernank** [comment]
Awesome, thanks!

**Comment by ahernank** [comment]
Will merge this now, and we can check that the HTML on the website looks all good & then make another quick check on Colab. :)

**Comment by ahernank** [comment]
Just a small thing here, @KellyLBennett - the HTML didn't seem to render correctly for one of the cells below in [here](https://anopheles-genomic-surveillance.github.io/workshop-5/module-3-stats.html) (all the other ones on this & the other modules are looking great): 

```
ag3.plot_samples_interactive_map(sample_query="release == '3.0'", basemap='worldimagery')
```

Would be great to re-run this one so the map is showing, on a new PR, if it isn't too much trouble! Usually this happens if the widgets changed between saves.

**Pull request merged**
